---
  - name: Ensure port 8080 is open
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: yes
    notify:
    - reload_firewalld
    
  - name: Flush handlers
    meta: flush_handlers

  - name: Install Jenkins using Jeff Geerling's Galaxy module
    include_role:
      name: geerlingguy.jenkins
    vars:
      - jenkins_hostname: build.home

# tasks file for jenkins
  - name: Ensure Hashicorp Yum repo is present
    yum_repository:
      name: hashicorp
      description: Hashicorp Stable - $basearch
      baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
      gpgkey: https://rpm.releases.hashicorp.com/gpg
      enabled: yes
      gpgcheck: yes

  - name: Ensure packer is installed
    yum:
      name:
      - packer
      state: present

  - name: Create a symbolic link
    file:
      src: /usr/bin/packer
      dest: /usr/bin/packer.io
      state: link
