node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {

        dir("${env.WORKSPACE}/jenkins-builder"){
            app = docker.build("dscarf/jenkins-builder:${env.BUILD_ID}")
            sh "pwd"
        }
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.ID}")
            app.push("latest")
        }
    }
}