- name: Patch all 
  hosts: all
  gather_facts: true
  
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  handlers:
  - name: reboot_node
    reboot: